version: '3'
services:
    stock-angular:
      image: stock-angular
      container_name: stock-angular
      build: ../front-stock
      ports:
        - 81:80
      networks:
        - stock-network
    stock:
      build: .
      container_name: stock
      entrypoint:  dockerize -template ./.docker/app/.env:.env -wait tcp://db-stock:3306 -timeout 40s ./.docker/entrypoint.sh
      environment:
        - DB_HOST=127.0.0.1
        - DB_PORT=3307
        - DB_DATABASE=api_stock
        - DB_USERNAME=leiviton
        - DB_PASSWORD=lorenzo2005
      volumes:
        - .:/var/www
      networks:
        - stock-network
      depends_on:
        - db-stock
        - redis-stock

    nginx-stock:
      build: .docker/nginx
      container_name: nginx-stock
      restart: always
      tty: true
      ports:
        - "8001:80"
      volumes:
        - .:/var/www
      networks:
        - stock-network
      depends_on:
        - stock
    db-stock:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db-stock
      restart: always
      tty: true
      ports:
        - "3306:3305"
      volumes:
        - ./.docker/dbdata:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=laravel
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=root
      networks:
        - stock-network

    redis-stock:
      image: redis:alpine
      container_name: redis-stock
      expose:
        - 6379
      networks:
        - stock-network

networks:
  stock-network:
    driver: bridge
