version: '3'
services:
    rabbit:
      image: "rabbitmq:3-management"
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"
        ports:
          - "15672:15672"
          - "5672:5672"
    stock:
      build: .
      container_name: stock
      entrypoint:  dockerize -template ./.docker/app/.env:.env -wait tcp://10.0.0.36:3306 -timeout 40s ./.docker/entrypoint.sh
      environment:
        - DB_HOST=10.0.0.36
        - DB_PORT=3306
        - DB_DATABASE=api_stock
        - DB_USERNAME=b2abd
        - DB_PASSWORD=leiviton01
        - APP_URL=http://10.0.108.137:8001
      volumes:
        - .:/var/www
      networks:
        - stock-network
      depends_on:
        - redis-stock

    nginx-stock:
      build: .docker/nginx
      container_name: nginx-stock
      restart: always
      tty: true
      ports:
        - "8001:80"
      volumes:
        - .:/var/www
      networks:
        - stock-network
      depends_on:
        - stock

    redis-stock:
      image: redis:alpine
      container_name: redis-stock
      expose:
        - 6379
      networks:
        - stock-network

networks:
  stock-network:
    driver: bridge
